apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  # Main application
  - name: node-app
    image: node-k8s-demo:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
  
  # Sidecar: nginx reverse proxy
  - name: nginx-sidecar
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config

