apiVersion: v1
kind: Pod
metadata:
  name: node-app-v1
  labels:
    app: node-demo
    version: v1
spec:
  containers:
  - name: node-app
    image: node-k8s-demo:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 3000

