apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: node-demo
    version: v1
spec:
  containers:
  - name: node-app
    image: node-k8s-demo:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"

