apiVersion: v1
kind: Namespace
metadata:
  name: auto-limited

---
# LimitRange sets defaults and boundaries
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: auto-limited
spec:
  limits:
  # Container limits
  - type: Container
    default:                    # Default limits (if not specified)
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:             # Default requests (if not specified)
      cpu: "100m"
      memory: "128Mi"
    max:                        # Maximum allowed
      cpu: "2"
      memory: "2Gi"
    min:                        # Minimum required
      cpu: "50m"
      memory: "64Mi"
    maxLimitRequestRatio:       # Max ratio of limit/request
      cpu: "4"
      memory: "4"
  
  # Pod limits (sum of all containers)
  - type: Pod
    max:
      cpu: "4"
      memory: "4Gi"
  
  # PVC limits
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "50Gi"


