# Headless Service (required for StatefulSet)
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None        # Headless service
  selector:
    app: nginx

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "web"     # Must match service name above
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: web
        command:
        - sh
        - -c
        - |
          echo "I am $(hostname)" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'

