apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: rotating-secret
                  key: api-key
