apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: node-app
    image: node-k8s-demo:v1
    ports:
    - containerPort: 3000
  - name: nginx-sidecar
    image: nginx:alpine
    ports:
    - containerPort: 80
