apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-checker
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  successfulJobsHistoryLimit: 6  # Keep 1 hour of history
  failedJobsHistoryLimit: 6
  concurrencyPolicy: Allow  # Allow concurrent checks
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300  # 5 minutes max
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: checker
            image: curlimages/curl:latest
            command:
            - sh
            - -c
            - |
              echo "Health check starting at $(date)"
              
              # Check frontend
              if curl -f -m 5 http://frontend-service:80/health; then
                echo "✅ Frontend healthy"
              else
                echo "❌ Frontend unhealthy"
                exit 1
              fi
              
              # Check backend
              if curl -f -m 5 http://backend-service:3000/health; then
                echo "✅ Backend healthy"
              else
                echo "❌ Backend unhealthy"
                exit 1
              fi
              
              # Check database (example)
              # if pg_isready -h db-service -p 5432; then
              #   echo "✅ Database healthy"
              # else
              #   echo "❌ Database unhealthy"
              #   exit 1
              # fi
              
              echo "Health check complete at $(date)"
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi

