apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  DATABASE_HOST: "postgres.default.svc.cluster.local"
  DATABASE_PORT: "5432"
  REDIS_HOST: "redis.default.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
stringData:
  database-username: "appuser"
  database-password: "SuperSecurePass123!"
  redis-password: "RedisPass456!"
  jwt-secret: "my-super-secret-jwt-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: node-k8s-demo:config-v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: myapp-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: database-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: database-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: myapp-secrets
              key: jwt-secret
        volumeMounts:
        - name: secret-files
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secret-files
        secret:
          secretName: myapp-secrets
          items:
          - key: jwt-secret
            path: jwt.key
