# This deployment will fail if it exceeds quota
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 15              # 👈 Exceeds pod quota (max 10)
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"


