apiVersion: v1
kind: Pod
metadata:
  name: emptydir-limited
spec:
  containers:
    - name: app
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 1Gi # Limit size
        medium: Memory # Use RAM instead of disk (faster, but limited)


