apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc
spec:
  accessModes:
  - ReadWriteOnce
  
  storageClassName: standard    # Use default StorageClass
  
  resources:
    requests:
      storage: 2Gi


