apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh", "-c", "echo 'Important data' > /data/important.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: backup-test-pvc


