# Frontend pods
apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
  labels:
    app: shop
    tier: frontend
    env: prod
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:alpine

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
  labels:
    app: shop
    tier: frontend
    env: prod
    version: v2
spec:
  containers:
  - name: nginx
    image: nginx:alpine

---
# Backend pods
apiVersion: v1
kind: Pod
metadata:
  name: backend-1
  labels:
    app: shop
    tier: backend
    env: prod
    version: v1
spec:
  containers:
  - name: app
    image: node:18-alpine
    command: ['sleep', '3600']

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-2
  labels:
    app: shop
    tier: backend
    env: dev
    version: v2
spec:
  containers:
  - name: app
    image: node:18-alpine
    command: ['sleep', '3600']

---
# Database pods
apiVersion: v1
kind: Pod
metadata:
  name: database-1
  labels:
    app: shop
    tier: database
    env: prod
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: password123


