apiVersion: v1
kind: Service
metadata:
  name: multi-port-service
spec:
  selector:
    app: node-demo
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: metrics
    port: 9090
    targetPort: 9090
