apiVersion: v1
kind: Service
metadata:
  name: node-app-nodeport
spec:
  type: NodePort
  selector:
    app: node-demo
  ports:
  - port: 80              # Service port (internal)
    targetPort: 3000      # Pod port
    nodePort: 30080       # Node port (external, optional)
    protocol: TCP

