# Development deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: development    # 👈 Specify namespace
  labels:
    app: web
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

---
# Service in same namespace
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: development    # 👈 Must match deployment namespace
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

---
# Staging deployment (same app, different namespace)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: staging        # 👈 Different namespace, same name!
  labels:
    app: web
    environment: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        environment: staging
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: staging
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80


