apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-rotation
spec:
  schedule: "0 0 * * *"  # Daily at midnight
  successfulJobsHistoryLimit: 7  # Keep a week of history
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  # Don't overlap log rotations
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800  # 30 minutes max
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: log-rotator
            image: busybox
            command:
            - sh
            - -c
            - |
              echo "Starting log rotation at $(date)"
              LOG_DIR="/logs"
              ARCHIVE_DIR="/logs/archive"
              
              # Create archive directory
              mkdir -p $ARCHIVE_DIR
              
              # Find logs older than 7 days
              echo "Finding old log files..."
              find $LOG_DIR -name "*.log" -mtime +7 -type f | while read logfile; do
                echo "Archiving: $logfile"
                filename=$(basename $logfile)
                gzip -c $logfile > $ARCHIVE_DIR/${filename}.$(date +%Y%m%d).gz
                rm $logfile
              done
              
              # Delete archives older than 30 days
              echo "Cleaning up old archives..."
              find $ARCHIVE_DIR -name "*.gz" -mtime +30 -delete
              
              # Report disk usage
              echo "Current disk usage:"
              du -sh $LOG_DIR
              
              echo "Log rotation complete at $(date)"
            volumeMounts:
            - name: logs
              mountPath: /logs
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
          volumes:
          - name: logs
            hostPath:
              path: /var/log/myapp
              type: DirectoryOrCreate
            # Alternative: Use PVC for persistent logs
            # persistentVolumeClaim:
            #   claimName: logs-pvc

